USE BeantasticDB;
GO

CREATE TABLE [dbo].[BeanClass](
	[BEANCLASSID] [INT] IDENTITY(1,1) NOT NULL,
	[NAME] [VARCHAR] (30) NOT NULL,
	[DESCRIPTION] [VARCHAR] (100) NOT NULL
	CONSTRAINT [PK_BeanClass] PRIMARY KEY CLUSTERED 
	(
		[BEANCLASSID] ASC
	)
);
GO